import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Portfolio
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://studentambassadors.microsoft.com/" className={styles.card}>
            <h2>Project 1</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://purple-water-0b08b5f0f.azurestaticapps.net/" className={styles.card}>
            <h2>Project 2</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/saragibby"
            className={styles.card}
          >
            <h2>Project 3</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://garagehackbox.azurewebsites.net/hackathons/2364/details/general"
            className={styles.card}
          >
            <h2>Project 4</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://microsoft.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sara Gibbons - Azure Static Web App Demo
        </a>
      </footer>
    </div>
  )
}
