import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Portfolio
        </h1>

        <p className={styles.description}>
          Sara Gibbons - Software Engineer
          <br/>
        </p>

        <div className={styles.grid}>
          <a href="https://studentambassadors.microsoft.com/" className={styles.card}>
            <h2>Project 1</h2>
            <p>Current project building out as part of team at Microsoft.</p>
          </a>

          <a href="https://purple-water-0b08b5f0f.azurestaticapps.net/" className={styles.card}>
            <h2>Project 2</h2>
            <p>Microsoft Global Hackathon 2021 - Amplify Women In Tech</p>
          </a>

          <a
            href="https://github.com/saragibby"
            className={styles.card}
          >
            <h2>Project 3</h2>
            <p>GitHub profile to see all my latest work and open source contributions.</p>
          </a>

          <a
            href="https://garagehackbox.azurewebsites.net/hackathons/2364/details/general"
            className={styles.card}
          >
            <h2>Project 4</h2>
            <p>
              DevRel Fix/Hack/Learn 2022 - Amplify refinement and engagement
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://microsoft.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Sara Gibbons - Azure Static Web App Demo
        </a>
      </footer>
    </div>
  )
}
